### ISSUE TITLE
Can we get it to check the wpa password ?

### ISSUE THREAD

**Issue by minanagehsalalma** [Fahad-M/NetworkStealer#1]

**Comment by quantumcore** [comment]
Might be able to add this, Sorry for the late reply. Okay I'm gonna add this feature now.

**Comment by minanagehsalalma** [comment]
@quantumcore  thanks ...  about the dns spoofing does the tool launch it or i have to do it manually? !

**Comment by quantumcore** [comment]
@minanagehsalalma You have to do it manually, NS Just starts a phish server.

**Comment by minanagehsalalma** [comment]
> @minanagehsalalma You have to do it manually, NS Just starts a phish server.

Why mot implement it ? How can i do it on windows?

**Comment by quantumcore** [comment]
Try this tool; https://github.com/Trackbool/DerpNSpoof

**Comment by minanagehsalalma** [comment]
> Try this tool; https://github.com/Trackbool/DerpNSpoof

Does this work on windows?  I mean that he said you need root permission

**Comment by quantumcore** [comment]
Try running as Administrator. It should work.

**Comment by minanagehsalalma** [comment]
it doesn't work

'ip' is not recognized as an internal or external command,
operable program or batch file.
[93m    [!] Cannot get your local IP addres, please write it: [0m192.168.1.8
Traceback (most recent call last):
  File "DerpNSpoof.py", line 106, in <module>
    from scapy.all import *
  File "C:\Users\ sdads
\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scapy\all.py",
line 18, in <module>
    from scapy.arch import *
  File "C:\Users\ sdads
\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scapy\arch\__init__.py",
line 67, in <module>
    from scapy.arch.windows import *  # noqa F403
  File
"C:\Users\sdads\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scapy\arch\windows\__init__.py",
line 56, in <module>
    from scapy.arch.pcapdnet import NPCAP_PATH, get_if_raw_addr, \
ImportError: cannot import name 'NPCAP_PATH' from 'scapy.arch.pcapdnet'
(C:\Users\ sdads
\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scapy\arch\pcapdnet.py)
