### ISSUE TITLE
An android wifi manager clone

### ISSUE THREAD

**Issue by minanagehsalalma** [Fahad-M/NetworkStealer#2]
Just like the wifi manager but with the targeted network opened without being able to exit wothout entering the password.

**Comment by quantumcore** [comment]
I don't understand what you mean by that, Sounds interesting though. Can you explain in more detail? 
@minanagehsalalma

**Comment by quantumcore** [comment]
Man I ain't getting notifications for issues and stuff. Sorry for the late reply.

**Comment by minanagehsalalma** [comment]
> I don't understand what you mean by that, Sounds interesting though. Can you explain in more detail?
> @minanagehsalalma

Here is an example of what i am talking about https://github.com/wifiphisher/wifiphisher/pull/1175   
But for android.
